### ISSUE TITLE
How did you get this mode-line ?

### ISSUE THREAD

**Issue by ghost** [emacsfodder/emacs-theme-darktooth#12]
I installed the theme, but with or without powerline enabled, I don't get the same modeline as in your screenshots. It is very elegant and minimal. Could you please tell me which one it is?

**Comment by jasonm23** [comment]
I was using - https://gist.github.com/jasonm23/8554119

**Comment by ghost** [comment]
Thank you a lot!
If any one else is interested, after many googling, I found [this post](http://amitp.blogspot.fr/2011/08/emacs-custom-mode-line.html) that may come from the original author.
[edit] the link is already on the source code [/edit]
