### ISSUE TITLE
The colors used by visual selection and hl-line-mode are too similar.

### ISSUE THREAD

**Issue by gujiaxi** [emacsfodder/emacs-theme-darktooth#28]
I set `(global-hl-line-mode t)` to highlight the current line.

![Imgur](http://i.imgur.com/wFDkcPp.png)

The selection region is from _buffer_ to _want_. The color dissimilarity is very low as the screenshot shows.

**Comment by jasonm23** [comment]
I think a darker color is ok for hl-line.  Agreed?

**Comment by jasonm23** [comment]
Different hue - let's say deep purple?

**Comment by gujiaxi** [comment]
Yes, in my humble opinion, the hl-line color doesn't need to highly contrast to the background too much.

**Comment by jasonm23** [comment]
Agreed

**Comment by jasonm23** [comment]
Fixed in #29
