### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by 2mac** [emacsfodder/emacs-theme-darktooth#4]
What are the terms of use?

**Comment by jasonm23** [comment]
I'll add in the licence, It'll be MIT.

**Comment by 2mac** [comment]
Might I suggest the ISC license instead? It's basically MIT, but without any of the ambiguous language like "substantial portions".

**Comment by jasonm23** [comment]
I'll take a look

**Comment by jasonm23** [comment]
I'll leave this as MIT.
