### ISSUE TITLE
Darktooth Does Not Explicitly Set org-document-title

### ISSUE THREAD

**Issue by ska2342** [emacsfodder/emacs-theme-darktooth#43]
Hi,

Today, I found that on my installation of Emacs the font for org-document-title was a pretty dark blue on Darktooth's dark background.  In a default Emacs session (-Q) this is not the case.

This time, I could hunt the problem down to zenburn theme being installed.  It just sat there in `~/.emacs.d/elpa/zenburn-theme....`. I do not load it explicitly, but it is listed in `package-selected-packages` in my custom.el. If I remove it from that variable, everything works.

My guess here is, that themes will set faces when being loaded even if they are not used.  Mind that I am not really familiar with the themes machinery in Emacs.

I'd like to clarify in this ticket if Darktooth should set more faces explicitly to generate reproducible behavior. If yes, I'll happily provide a PR for this face (and others when I come across them).

Best regards,
stefan

**Comment by dieggsy** [comment]
@ska2342 for future reference, as @jasonm23 showed me, you don't have to wait to come across them. You can use `autothemer-generate-templates` to see which faces are not set by the current theme. I've been playing around with and thinking about some like the org title and the shadow face, but haven't settled on anything definitive for them yet.

**Comment by ska2342** [comment]
Thanks for pointing out :+1: – I already used it over in PR #42 once. I'd only want to work on some faces when I actually see and use them. Good news is, I can finally use customize again. Yay. Sorry, a bit offtopic, I guess.

**Comment by jasonm23** [comment]
Hi Stefan,

Zenburn faces will (should!) only be applied when the theme is loaded.

Emacs will apply multiple themes by default (as they are loaded), anecdotally this is usually unwanted by modern users, or at least unexpected.

To ensure no other themes are active, its necessary to unload any active themes before applying your chosen theme.

If not, face definitions which are not customized by the chosen theme will remain as they were by previously loaded themes (from the current Emacs session.)

**Comment by jasonm23** [comment]
Please note​ that installing a theme isn't enough to apply it, however, themes are arbitrary Lisp, so anything could be done in their code, including auto loading.

**Comment by ska2342** [comment]
Hi @jasonm23,

I am not familiar with how themes are loaded.  I had the Zenburn theme on the `package-selected-packages` variable in my `custom.el`.  Customize put it there, I certainly didn't.

Only if I remove the other themes from there, the Darktooth finally shows all the things beautifully. That was probably the reason for my weird problems in #42, too.

I ended up in this situation by just installing a few themes and enabling them for testing. I thought, only the theme that I finally settled on would be active.

Would you like to set more faces explicitly? It would avoid clashes with other themes that may have been loaded without the user knowing it (like me). On the other hand, it is more effort.  

Feel free to close this issue if you prefer not setting all faces explicitly.

Cheers,
stefan

**Comment by jasonm23** [comment]
The goal of Darktooth is never to be part of a composite set of themes​, so adding explicit support for faces is definitely the way to go.

If you'd like to add support for missing Org mode (or any other modes you use) I'm likely to accept them if they follow the standard palette.

Please note: Consider the colors in the lower half of the palette e.g. sienna etc. To be second class and avoided unless all the first class colors are illegible.

As always it speeds acceptance to provide a screenshot of the themed faces in context.

Thanks very much for your assistance and interest, it's much appreciated.
