### ISSUE TITLE
What's the deal with tag v4.0?

### ISSUE THREAD

**Issue by christianlask** [emacsfodder/emacs-theme-darktooth#50]
The code at https://github.com/emacsfodder/emacs-theme-darktooth/tree/v4.0 does not really look like an emacs-theme, does it? :grin: Or is it just me?

**Comment by jasonm23** [comment]
Thank you for catching that, v4.0 was a push from a completely different tree.  It's gone now. (It's my keyboard firmware)

**Comment by christianlask** [comment]
@jasonm23 You're welcome. And thank you for creating this wonderful theme :)
