### ISSUE TITLE
Wrong Flycheck error and warning colors

### ISSUE THREAD

**Issue by ANDRON94** [emacsfodder/emacs-theme-darktooth#53]
Hello,

First of all, I would like to thank you for creating such a cool theme!
But I found the strange color issue: when I working with flycheck mode errors are drawn with orange color and warnings are drawn with red. I think it should be vice versa(and, in my opinion, for warnings better to use yellow).
Screenshot with errors:
![error_snapshot_edited](https://user-images.githubusercontent.com/6495837/31344899-be11163a-ad1c-11e7-8c3e-7e17a564175c.png)
![error_with_helm_snapshot](https://user-images.githubusercontent.com/6495837/31344948-e7b19bea-ad1c-11e7-9e38-f6ef62678a24.png)

Screenshot with warnings:
![warning_snapshot_edited](https://user-images.githubusercontent.com/6495837/31344906-c228bde0-ad1c-11e7-9505-2ca8715687a0.png)
![warning_with_helm_snapshot](https://user-images.githubusercontent.com/6495837/31344963-ec41f79a-ad1c-11e7-8eb0-c9d4414fdfef.png)

P.S. And I'm not strong enough Emacs user to send PR to you. Sorry.

**Comment by dieggsy** [comment]
By default, darktooth-theme doesn't actually explicitly theme flycheck faces. I've opened a PR addressing this with some colors I had added in my custom fork.

FWIW, you don't need to know that much lisp for this - just checkout `M-x describe-face` and type `flycheck-` if you have a completion system like ivy or helm, or `M-x customize-group RET flycheck-faces RET`. Then you can see the face names that pertain to that feature. At that point, it's just a matter of following the structure in the theme code, which is pretty self explanatory:

```
(default                                   (:foreground darktooth-light0 :background darktooth-dark0))
(cursor                                    (:background darktooth-light0))
(link                                      (:foreground darktooth-bright_blue :underline t))
(link-visited                              (:foreground darktooth-bright_blue :underline nil))
```

So more generally,

```
(face-name      face-spec)
```

Where the face spec tends to be fairly self explanatory if you take the others as templates.

**Comment by jasonm23** [comment]
Thanks for adding the mode support PR

**Comment by ANDRON94** [comment]
Hello, thank you!
I just didn't know how theme configuration is working. So, thanks for your explanation. I will try to send PR next time =)
