### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by Poorchop** [emacsfodder/emacs-theme-darktooth#62]
I've spent a lot of time trying to revamp the [base TextMate theme file](https://github.com/Poorchop/darktooth-theme-ports/blob/master/textmate-theme-darktooth/Darktooth.tmTheme) that provides the foundation for a lot of the ports. I have been using [this gruvbox theme](https://github.com/Briles/gruvbox) as the basis since it looks pretty good to me in other editors and it includes a lot more selectors that help make the theme look a lot better in editors like Sublime Text.

That gruvbox theme has selectors for Markdown and other file types/editing modes. The emacs theme doesn't do any syntax highlighting for Markdown at all. Some elements to consider include Markdown headings, inline code, quoted text, and lists. I could just set the colors myself but it's always good to have an official template in the emacs theme for guidance.

**Comment by jasonm23** [comment]
Sorry for responding to this one so late.  Could you list the faces you'd like covered + suggestions or submit a pull request if you have an idea for the markdown theming.

**Comment by Poorchop** [comment]
This is what I had come up with a while ago for a few of my ports. I think that these are the most important scopes to cover although there is room for better coverage. It has just been a while since I last edited the theme so I'll need to familiarize myself with it again.

![untitled](https://user-images.githubusercontent.com/5256208/42899943-93d8b902-8a95-11e8-9c72-8168d58afcaa.png)

**Comment by jasonm23** [comment]
I make those colors...

```

bold:            #FB6A16
italic:          #FB6A16
link-title:      #427978
link:            #FCF3B4
separator:       #7F7061
inline-code:     #719586
code-block:      #719586
unnumbered-list: #AC9A85
numbered-list:   #C77089
heading:         #55888B

```

**Comment by jasonm23** [comment]
Adding markdown support to:

- [x] gruvbox-dark-hard-theme
- [x] gruvbox-dark-medium-theme
- [x] gruvbox-dark-soft-theme
- [x] gruvbox-light-hard-theme
- [x] gruvbox-light-medium-theme
- [x] gruvbox-light-soft-theme
- [x] gruvbox-theme
- [x] creamsody-dark-theme
- [x] creamsody-darker-theme
- [x] creamsody-theme
- [x] darktooth-dark-theme
- [x] darktooth-darker-theme
- [x] darktooth-theme
- [x] vegetative-theme
- [x] sakura-theme
- [x] cyanometric-theme
- [x] orangey-bits-theme
