### ISSUE TITLE
thick line on fringe

### ISSUE THREAD

**Issue by ratnesh1729** [emacsfodder/emacs-theme-darktooth#70]
(Wanted to thank first for all the theme - this has been very useful)

Currently this theme displays something like this: 
![fringe-_base-16](https://user-images.githubusercontent.com/11953515/72685778-3d8d3a00-3aa2-11ea-8dce-a9327c32148b.png)

When I use some other theme - it shows nice thick line on the fringe (please see below)
![fringe_old](https://user-images.githubusercontent.com/11953515/72685780-40882a80-3aa2-11ea-8948-8d1d35217c63.png)

How can I set it similar to the one above ?

Best,

**Comment by jasonm23** [comment]
Sorry for the late response to this issue.

The Git Gutter family of packages would control if this fringe type is available.

I think this issue is now solved/covered.

**Comment by jasonm23** [comment]
https://github.com/emacsfodder/emacs-theme-darktooth/blob/c344fc80647338e137cd78a4c30bfad41ab56736/darktooth.el#L238-L265 (locked to revision)
