### ISSUE TITLE
Symbol’s value as variable is void: darktooth-light2

### ISSUE THREAD

**Issue by xmathe** [emacsfodder/emacs-theme-darktooth#74]
Darktooth is my default and ultimate color theme.
After last package upgrade theme (either darktooth or darktooth-darker or darktooth-dark) can't be loaded saying *"Symbol’s value as variable is void: darktooth-light2"*
Can it be fixed?
Thanks!

**Comment by jasonm23** [comment]
Fixed in 383c33055bc1ccf0a898aebb10c16eb44ad84a3f
