### ISSUE TITLE
hl-line has the same background color as region face

### ISSUE THREAD

**Issue by tuhdo** [emacsfodder/emacs-theme-darktooth#8]
When `hl-line-mode` is turned on, it's impossible to distinguish between the highlighted region and the highlighting line. I suggest that we should change either `region` or `hl-line` background color to `#1a1a1a` (which is `gray10`).

**Comment by tuhdo** [comment]
I suggest that we should assign `#1a1a1a` to `region`, since it makes the region more visible and stand out, and `hl-line` is subtle enough without getting in the way.

**Comment by jasonm23** [comment]
There's a range of `darktooth-dark_` colors in the palette.  You may pick one for `hl-line`.

**Comment by tuhdo** [comment]
For `hl-line`, I picked this color from the pallete and it looks quite good: `#1e1c1a`, also I prefer this color for `region`. What do you think?

**Comment by jasonm23** [comment]
Thanks I'll make that hl-line.

Region won't be changing.

**Comment by jasonm23** [comment]
`#1e1c1a` [is **not** in the palette](https://github.com/emacsfodder/emacs-theme-darktooth/blob/master/darktooth-theme.el#L21-L84).  Please note there will be no deviations from the darktooth palette.

I will set `hl-line` to  `darktooth-dark_blue`

**Comment by tuhdo** [comment]
I don't know. I picked it from [here](https://github.com/emacsfodder/emacs-theme-editor/blob/gh-pages/js/starter-themes.coffee). I thought that was the same thing used on your theme creator app.

**Comment by jasonm23** [comment]
f9759eff6450d0e72a542497079894765d9f75c1

**Comment by jasonm23** [comment]
Ahh, I see.  No that's not really the same theme anymore, I should probably rename it.

**Comment by jasonm23** [comment]
Renamed the theme editor starter theme to **DarkBooth** :+1: (yah, great name right ;) )

**Comment by jasonm23** [comment]
https://emacsfodder.github.io/emacs-theme-editor/ updated.
