### ISSUE TITLE
Make header line visible

### ISSUE THREAD

**Issue by tuhdo** [emacsfodder/emacs-theme-darktooth#9]
We should make the header line visible to let user know a package that uses a header line is really activated.

``` elisp
(set-face-attribute 'header-line nil
                        :box '(:line-width -1 :style released-button))
```

Or at least, make `helm-source-header` more distinctive with its candidates. This definitely looks better in Helm:

``` elisp
(set-face-attribute 'helm-source-header nil
                        :box '(:line-width -1 :style released-button))
```

**Comment by jasonm23** [comment]
I'm not sure there's value in it.

I could add a developer note to the readme to explain that it's hidden.   So using another theme to test is a good idea.

**Comment by tuhdo** [comment]
At least make it a box in Helm. Otherwise Helm is more difficult to use in the theme. Probably you are using Ido only?

**Comment by jasonm23** [comment]
It's specifically removed to make helm look better.

The header line is ugly as ____

**Comment by tuhdo** [comment]
You don't need to remove but make it look better. Here is [an example of how Zenburn handles it](https://cloud.githubusercontent.com/assets/4818719/7496331/b5233b60-f43d-11e4-8976-c85f46644a27.gif). My suggestion is how exactly Zenburn beautified Helm header.

And actually you don't remove it but make it look difficult to use.

**Comment by jasonm23** [comment]
I'll give it some thought.  I'm cooking my family dinner right now.

**Comment by jasonm23** [comment]
This got fixed in a recent commit

**Comment by jasonm23** [comment]
Box isn't used but it has a background color difference to emphasise the header line
